name: CI Pipeline


jobs:
  build:
    runs-on: self-hosted     
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test
